#pragma once
#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_ttf.h>
#include <GL/glew.h>
#include <SDL2/SDL_opengl.h>
#include <GL/glu.h>
#include <GL/freeglut.h>
#include <stdio.h>
#include <string>
#include <vector>
#include <memory>
#include <unordered_map>
#include <functional>
#include <filesystem>
#include <set>
#include <fstream>
#include "../Hidden/Aliases.h"
#include "../Hidden/CPalette.h"
#include "../Hidden/CPoint2F.h"
#include "../Hidden/CRectF.h"
#include "../Hidden/CPoint2.h"
#include "Framework/WorldStructure/CMob.h"
#include "Framework/CSceneBase.h"
#include "../Hidden/CSDL_Deleter.h"
#include "../Hidden/Typedefs.h"
#include "../Hidden/CSize.h"
#include "../Hidden/CSizeF.h"
#include "../Hidden/ECursorTypes.h"
#include "Framework/CGuiWindowBase.h"
#include "Framework/WorldStructure/CObject.h"
#include "Framework/WorldStructure/CTile.h"
#include "Framework/WorldStructure/CMapArea.h"
#include "Framework/WorldStructure/CWorldMap.h"
#include "Framework/CInventory.h"
#include "Framework/CObjectDescription.h"
#include "Framework/CObjectsContent.h"
#include "Framework/CScenesCollection.h"
#include "../Hidden/CVector2.h"
#include "../Hidden/CVector3.h"
#include "../Hidden/CVertex.h"
#include "../Hidden/CMaterial.h"
#include "../Hidden/CMesh.h"
